dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - libglu1-mesa-dev
      - xorg-dev
install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libassimp-dev libglm-dev graphviz libxcb-dri3-0 libxcb-present0 libpciaccess0 cmake libpng-dev libxcb-dri3-dev libx11-dev libx11-xcb-dev libmirclient-dev libwayland-dev libxrandr-dev
  - wget -O vulkansdk-linux-x86_64-1.1.85.0.run https://vulkan.lunarg.com/sdk/download/1.1.85.0/linux/vulkansdk-linux-x86_64-1.1.85.0.run
  - chmod +x vulkansdk-linux-x86_64-1.1.85.0.run
  - ./vulkansdk-linux-x86_64-1.1.85.0.run
  - export VULKAN_SDK=$TRAVIS_BUILD_DIR/VulkanSDK/1.1.85.0/x86_64
script:
  - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 cmake .
  - cmake -DPAGE_GLFW_ENABLED=ON -DDIREWOLF_VULKAN_ENABLED=ON --build .
